### ISSUE TITLE
setup.cfg: LICENSE.md should be LICENSE

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/CDP-Socket#22]
https://github.com/kaliiiiiiiiii/CDP-Socket/blob/91882101aabac4cba5757a2f824b80d9300a64f2/setup.cfg#L3

install says

> warning: no files found matching 'LICENSE.md'

**Comment by ttlns** [comment]
https://github.com/kaliiiiiiiiii/CDP-Socket/commit/a6e956efe6ee327f2d89427d7c343f984f9e59a3
Thanks

**Comment by ttlns** [comment]
`cdp-socket>=1.2.4.1` released
