### ISSUE TITLE
requirements.txt: remove dev dependencies

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/CDP-Socket#23]
these belong to a separate file, something like requirements-dev.txt

https://github.com/kaliiiiiiiiii/CDP-Socket/blob/91882101aabac4cba5757a2f824b80d9300a64f2/requirements.txt#L5-L7

**Comment by ttlns** [comment]
mhh why tho? This doesn't affect the package itsself.
requirements are defined at https://github.com/kaliiiiiiiiii/CDP-Socket/blob/a014832bb888ee3c59c5f0b1625c63ca6a080998/setup.py#L4

**Comment by milahu** [comment]
aah, sorry, requirements.txt is ignored by my installer, nevermind
